
import javax.swing.JOptionPane;

public class tela extends javax.swing.JFrame {

    private int numeroAleatorio;  // Número aleatório para adivinhar
    private int tentativasRestantes = 10;  // Total de tentativas permitidas
    private String palpitesAnteriores = "";  // Armazena os palpites anteriores
    private int numeroLimite = 11; //Limite do número aleatório

    public tela() {
        initComponents();
        gerarNumeroAleatorio();
        atualizarTentativas();
    }

    private void gerarNumeroAleatorio() {
        numeroAleatorio = (int) (Math.random() * numeroLimite);  // Gera um número entre 0 e o numeroLimite definido anteriormente
    }

    private void atualizarTentativas() {
        jContadorTentativas.setText(String.valueOf(tentativasRestantes));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jNumeroUsuario = new javax.swing.JTextField();
        jValidadorNumero = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPalpitesAnteriores = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDicasNumMaiorMenor = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jContadorTentativas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo do Adivinha");
        setMaximumSize(new java.awt.Dimension(340, 600));
        setMinimumSize(new java.awt.Dimension(340, 600));
        setPreferredSize(new java.awt.Dimension(340, 600));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel1.setText("Adivinhe um número entre 0 e 10:");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setText("Digite aqui seu palpite:");

        jNumeroUsuario.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jNumeroUsuario.setForeground(new java.awt.Color(0, 0, 102));
        jNumeroUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jNumeroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNumeroUsuarioActionPerformed(evt);
            }
        });

        jValidadorNumero.setFont(new java.awt.Font("sansserif", 1, 70)); // NOI18N
        jValidadorNumero.setText("?");
        jValidadorNumero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jValidadorNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValidadorNumeroActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel2.setText("Últimos palpites:");

        jPalpitesAnteriores.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jPalpitesAnteriores.setForeground(new java.awt.Color(0, 0, 102));
        jPalpitesAnteriores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPalpitesAnteriores.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel5.setText("Tentativas restantes:");

        jDicasNumMaiorMenor.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jDicasNumMaiorMenor.setForeground(new java.awt.Color(0, 0, 102));
        jDicasNumMaiorMenor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDicasNumMaiorMenor.setText("Digite primeiro o seu palpite...");
        jDicasNumMaiorMenor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel7.setText("Dica:");

        jContadorTentativas.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jContadorTentativas.setForeground(new java.awt.Color(204, 0, 0));
        jContadorTentativas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jContadorTentativas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPalpitesAnteriores, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jContadorTentativas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jDicasNumMaiorMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jNumeroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jValidadorNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNumeroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jValidadorNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDicasNumMaiorMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPalpitesAnteriores, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jContadorTentativas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("Adivinhe um número entre 0 e 10:");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jValidadorNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValidadorNumeroActionPerformed
        jNumeroUsuarioActionPerformed(evt);

    }//GEN-LAST:event_jValidadorNumeroActionPerformed

    private void jNumeroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumeroUsuarioActionPerformed
        try {
            int palpiteUsuario = Integer.parseInt(jNumeroUsuario.getText());

            // Verifica se o palpite está dentro do intervalo permitido
            if (palpiteUsuario < 0 || palpiteUsuario >= numeroLimite) {
                JOptionPane.showMessageDialog(this,
                        "O palpite deve estar entre 0 e " + (numeroLimite - 1) + "! \nTente novamente",
                        "Atenção",
                        JOptionPane.WARNING_MESSAGE);
            } else {
                validarPalpite(palpiteUsuario);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Caracter inválido.\nTente novamente",
                    "Atenção",
                    JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jNumeroUsuarioActionPerformed

    private void reiniciarJogo() {
        tentativasRestantes = 10;
        palpitesAnteriores = "";
        gerarNumeroAleatorio();
        atualizarTentativas();
        jPalpitesAnteriores.setText("");
        jDicasNumMaiorMenor.setText("Digite primeiro o seu palpite...");
        jNumeroUsuario.setText("");
    }

    private void validarPalpite(int palpiteUsuario) {
        if (tentativasRestantes > 0) {
            tentativasRestantes--;
            atualizarTentativas();

            if (palpiteUsuario == numeroAleatorio) {
                JOptionPane.showMessageDialog( this, "Você acertou! \nO número secreto é o: "+numeroAleatorio, "Parabéns", JOptionPane.INFORMATION_MESSAGE);
                reiniciarJogo();
            } else {
                if (!palpitesAnteriores.isEmpty()) {
                    palpitesAnteriores = palpiteUsuario + ", " + palpitesAnteriores; // Adiciona vírgula se houver palpites
                } else {
                    palpitesAnteriores = palpiteUsuario + " "; // Não adiciona vírgula se não houver palpites
                }
                

                jPalpitesAnteriores.setText(palpitesAnteriores);
                jDicasNumMaiorMenor.setText(palpiteUsuario < numeroAleatorio ? "O número é maior!" : "O número é menor!");

                if (tentativasRestantes == 0) {
                    JOptionPane.showMessageDialog(this,
                            "Suas tentativas acabaram! \nO número era: " + numeroAleatorio + ".",
                            "Aviso",
                            JOptionPane.ERROR_MESSAGE);

                    reiniciarJogo();
                }
            }
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jContadorTentativas;
    private javax.swing.JLabel jDicasNumMaiorMenor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jNumeroUsuario;
    private javax.swing.JLabel jPalpitesAnteriores;
    private javax.swing.JButton jValidadorNumero;
    // End of variables declaration//GEN-END:variables
}
